### PR TITLE
#164797970 Setup TravisCi to run tests

### PR DESCRIPTION
**Pull request by amaechi-chuks**
#### Description
This PR sets up  TravisCi to run tests

#### Type of change
- [x] Non-Breaking Change

#### How Has This Been Tested?
N/A

#### Checklist:
- [x] setup TravisCi

#### PT-ID
[#164797970](https://www.pivotaltracker.com/story/show/164797970)

#### Screenshots
N/A

#### Questions:
N/A

### CODE REVIEW

**Comment by walsamlee** [comment]
I noticed Travis CI is failing, any reason?

**Comment by amaechi-chuks** [comment]
> I noticed Travis CI is failing, any reason?
The test setup is still in progress. When it's done and pushed, it will pass.

**Comment by walsamlee** [comment]
> > I noticed Travis CI is failing, any reason?
> > The test setup is still in progress. When it's done and pushed, it will pass.

Ok

**Comment by sojida** [comment]
Nice work here @amaechi-chuks. However, we can wait for @vic3king to raise a PR on the test so that we can check your Travis setup before we merge this PR.

**Comment by amaechi-chuks** [comment]
> Looks good but why is the badge under the comment

Thanks for that observation. I will quickly fix it up.

**Pull request merged**
